const create = require('./create.js')
const sqlite3 = require('sqlite3').verbose()
const alterTable = require('./alter.js')
const db = new sqlite3.Database('test.db')
create(db, "music")
console.dir(alterTable)
console.log(alterTable)
// alterTable(db,"music", "Music_index", "primary key")
// alterTable(db, "music", "title", "text not null")
// alterTable(db, "music", "singer", "text")
// alterTable(db, "music", "genre", "text")
// alterTable(db, "music", "year", "integer")